# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_bot',
            field=models.BooleanField(default=1),
        ),
    ]
